title: Stack Problems
description: My Personal Stack Problems
author: Ramiro Alvaro
github: https://github.com/ramiroalvaro
about: Desarrollador Backend Python & Django
disqus_shortname:
google_analytics:

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fab fa-linkedin
      link: "https://linkedin.com/in/ramiro-alvaro"
    - icon: fab fa-github
      link: "https://github.com/ramiroalvaro"
    - icon: fas fa-envelope
      link: "mailto:ramiroalvaro@hotmail.com"
    - icon: fab fa-telegram-plane
      link: "https://t.me/ramiroalvaro"
    - icon: fab fa-whatsapp
      link: "https://wa.me/5531991387178"
      

share:
  twitter_username:
  fb_appid:

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://ramiroalvaro.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
