title: Blog
description: Blog Personal
author: Ramiro Alvaro
github: https://github.com/ramiroalvaro
about: Desenvolvedor Backend Python & Django
disqus_shortname:
google_analytics:

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://linkedin.com/in/ramiro-alvaro"
    - icon: fa-github
      link: "https://github.com/ramiroalvaro"
    - icon: fa-envelope
      link: "mailto:ramiroalvaro.ra@gmail.com"
      

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Sobre mí
      url: /about/
    - text: Mis proyectos
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://ramiroalvaro.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
